
---
spring:
    profiles: brix-postgres

    datasource:
        url: jdbc:postgresql://192.168.1.100:5432/bookmarks
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: org.postgresql.Driver
        username: bookmarks
        password: bookmarks
        hikari:
                url: jdbc:postgresql://192.168.1.100:5432/bookmarks
                pool-name: bookmarks-hikari-pool
                autoCommit: false
                connection-test-query: SELECT 1
                idleTimeout: 20000
                minimum-idle: 1
                maximumPoolSize: 5
